"""add time control columns

Revision ID: 6bab8cd6dbe4
Revises: 927361b0445b
Create Date: 2026-07-18 16:57:41.930425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bab8cd6dbe4'
down_revision: Union[str, Sequence[str], None] = '927361b0445b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('increment_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('white_clock_ms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('black_clock_ms', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('black_clock_ms')
        batch_op.drop_column('white_clock_ms')
        batch_op.drop_column('increment_seconds')
        batch_op.drop_column('initial_seconds')

    # ### end Alembic commands ###
