"""initial schema

Revision ID: 927361b0445b
Revises: 
Create Date: 2026-07-11 14:16:42.797747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927361b0445b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('player_color', sa.String(length=5), nullable=False),
    sa.Column('engine_elo', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=7), nullable=True),
    sa.Column('result_reason', sa.String(length=32), nullable=True),
    sa.Column('start_fen', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), server_default='play', nullable=False),
    sa.Column('pgn', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('player_accuracy', sa.Float(), nullable=True),
    sa.Column('blunders', sa.Integer(), nullable=True),
    sa.Column('mistakes', sa.Integer(), nullable=True),
    sa.Column('inaccuracies', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=8), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('loss_cp', sa.Integer(), nullable=False),
    sa.Column('score_cp', sa.Integer(), nullable=False),
    sa.Column('best_move_uci', sa.String(length=6), nullable=True),
    sa.Column('is_mate_swing', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'ply', name='uq_analysis_game_ply')
    )
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_results_game_id'), ['game_id'], unique=False)

    op.create_table('moves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=8), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=5), nullable=False),
    sa.Column('uci', sa.String(length=6), nullable=False),
    sa.Column('san', sa.String(length=16), nullable=False),
    sa.Column('fen_before', sa.Text(), nullable=False),
    sa.Column('think_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'ply', name='uq_moves_game_ply')
    )
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moves_game_id'), ['game_id'], unique=False)

    op.create_table('puzzles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=8), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('fen', sa.Text(), nullable=False),
    sa.Column('best_move_uci', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'ply', name='uq_puzzles_game_ply')
    )
    with op.batch_alter_table('puzzles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_puzzles_game_id'), ['game_id'], unique=False)

    op.create_table('srs_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('ease_factor', sa.Float(), server_default=sa.text('(2.5)'), nullable=False),
    sa.Column('correct_streak', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puzzle_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('srs_cards')
    with op.batch_alter_table('puzzles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_puzzles_game_id'))

    op.drop_table('puzzles')
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moves_game_id'))

    op.drop_table('moves')
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_results_game_id'))

    op.drop_table('analysis_results')
    op.drop_table('games')
    # ### end Alembic commands ###
